version: "3.8"
services:
  mongodb:
    image: mongo:latest
    volumes:
      - mongodb-data:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

  postgresql:
    image: postgres:latest
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  server:
    build: ./server
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - postgresql
    command: sh -c "npm install && npm run dev"
    volumes:
      - ./server:/src
    environment:
      MONGO_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_HOSTNAME: mongodb
      MONGO_PORT: 27017
      MONGO_DB: mongodb
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOSTNAME: postgresql
      POSTGRES_PORT: 5432

  client:
    build: ./client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev"
    environment:
      - NODE_ENV=${NODE_ENV}

volumes:
  mongodb-data:
  postgresql-data:
